### ISSUE TITLE
Crash in the Chat Activity in the release apk

### ISSUE THREAD

**Issue by batbrain7** [fossasia/susi_android#1425]
**Actual Behaviour**

On logging in, the app crashes on the chat screen.

**Expected Behaviour**

The app should not crash.

**Steps to reproduce it**

Log in to the app and wait for the chat screen to open

**LogCat for the issue**

**Would you like to work on the issue?**

Yes me and @arundhati24

**Comment by mariobehling** [comment]
java.lang.StackOverflowError: stack size 8MB
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timb
[TRUNCATED 500682 CHARS]
 timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at org.fossasia.susi.ai.MainApplication$ReleaseLogTree.log(MainApplication.java:73)
	at timber.log.Timber$Tree.prepareLog(Timber.java:532)
	at timber.log.Timber$Tree.e(Timber.java:450)
	at timber.log.Timber$1.e(Timber.java:306)
	at timber.log.Timber.e(Timber.java:83)
	at ai.kitt.snowboy.AppResCopy.copyFilesFromAssets(AppResCopy.java:39)
	at ai.kitt.snowboy.AppResCopy.copyFilesFromAssets(AppResCopy.java:31)
	at ai.kitt.snowboy.AppResCopy.copyResFromAssetsToSD(AppResCopy.java:63)
	at org.fossasia.susi.ai.data.UtilModel.copyAssetstoSD(UtilModel.kt:80)
	at org.fossasia.susi.ai.chat.ChatPresenter.initiateHotwordDetection(ChatPresenter.kt:94)
	at org.fossasia.susi.ai.chat.ChatActivity.initializationMethod(ChatActivity.kt:110)
	at org.fossasia.susi.ai.chat.ChatActivity.onCreate(ChatActivity.kt:79)
	at android.app.Activity.performCreate(Activity.java:6875)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2659)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2767)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1514)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6221)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

**Comment by iamareebjamal** [comment]
https://github.com/fossasia/susi_android/blob/development/app/src/main/java/org/fossasia/susi/ai/MainApplication.java#L75

These are recursive calls to the same method I pointed out in code review.

As there are release/debug/fdroid/play store versions, it is not just enough to test debug version. Before dev is merged into master, all 4 versions of the matrix must be checked to ensure each line of code works.

@arundhati24 @batbrain7

**Comment by batbrain7** [comment]
@iamareebjamal putting Timber.e method in the class produces the recursive call , can I put Log.e in that priority == Log.Error block ?

**Comment by arundhati24** [comment]
@iamareebjamal I see there is a recursive call because Timber has been used where it is actually being initialised.
The problem didn't occur with the Debug tree because this has not been done for the debug. It is the ReleaseLogTree class where we have Timber used. Shall this be replaced with the Android Log class here?

**Comment by iamareebjamal** [comment]
@batbrain7 @arundhati24 Yes. And this is why there is a need to test all versions before release

**Comment by iamareebjamal** [comment]
@batbrain7 @arundhati24 Please test the release apk manually so that we can merge dev into master and release new apk

**Comment by batbrain7** [comment]
[app-fdroid-release.apk.zip](https://github.com/fossasia/susi_android/files/2127967/app-fdroid-release.apk.zip)
[app-playStore-release.apk.zip](https://github.com/fossasia/susi_android/files/2127968/app-playStore-release.apk.zip)
