### ISSUE TITLE
App crashes on clicking on settings

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#1463]
Please see below error.
```
java.lang.IllegalStateException: currentFocus must not be null
at org.fossasia.susi.ai.skills.SkillsActivity.hideKeyboard(SkillsActivity.kt:174)
at org.fossasia.susi.ai.skills.SkillsActivity.handleOnLoadingFragment(SkillsActivity.kt:187)
at org.fossasia.susi.ai.skills.SkillsActivity.onOptionsItemSelected(SkillsActivity.kt:87)
at android.app.Activity.onMenuItemSelected(Activity.java:3381)
at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:407)
at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
at android.support.v7.app.AppCompatDelegateImplV9.onMenuItemSelected(AppCompatDelegateImplV9.java:674)
at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
at android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
at android.widget.AdapterView.performItemClick(AdapterView.java:310)
at android.widget.AbsListView.performItemClick(AbsListView.java:1164)
at android.widget.AbsListView$PerformClick.run(AbsListView.java:3154)
at android.widget.AbsListView.onTouchUp(AbsListView.java:4109)
at android.widget.AbsListView.onTouchEvent(AbsListView.java:3841)
at android.support.v7.widget.DropDownListView.onTouchEvent(DropDownListView.java:216)
at android.support.v7.widget.MenuPopupWindow$MenuDropDownListView.onTouchEvent(MenuPopupWindow.java:128)
at android.view.View.dispatchTouchEvent(View.java:10036)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2628)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2307)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2634)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2321)
at android.widget.PopupWindow$PopupDecorView.dispatchTouchEvent(PopupWindow.java:2277)
at android.view.View.dispatchPointerEvent(View.java:10258)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4500)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4365)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3905)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3958)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3924)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4051)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3932)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4108)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3905)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3958)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3924)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3932)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3905)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6309)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6283)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6244)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6415)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:187)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:323)
at android.os.Looper.loop(Looper.java:142)
at android.app.ActivityThread.main(ActivityThread.java:6221)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
```

**Comment by arundhati24** [comment]
Usually, IllegalStateException is used to indicate that a method has been invoked at an illegal or inappropriate time. The 'getCurrentFocus()' has been defined in Activity.java as follows : 
```
@Nullable
    public View getCurrentFocus() {
        return mWindow != null ? mWindow.getCurrentFocus() : null;
    }
```
Thus ```currentFocus``` on line 174 in [SkillsActivity.kt] is nullable.
The most probable cause of this crash seems to be absence of null check on currentFocus.
