### ISSUE TITLE
Crash In Settings Activity

### ISSUE THREAD

**Issue by codedsun** [fossasia/susi_android#1478]
**Actual Behaviour**
Crash on opening settings activity

**Expected Behaviour**

There should not be crash

**Steps to reproduce it**

Go to settings

**LogCat for the issue**
```
07-02 21:28:46.501 16474-16474/ai.susi.fdroid E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ai.susi.fdroid, PID: 16474
    java.lang.ArrayIndexOutOfBoundsException: length=6; index=-1
        at android.support.v7.preference.ListPreference.setValueIndex(ListPreference.java:207)
        at org.fossasia.susi.ai.skills.settings.ChatSettingsFragment.setLanguage(ChatSettingsFragment.kt:227)
        at org.fossasia.susi.ai.skills.settings.ChatSettingsFragment.onCreatePreferencesFix(ChatSettingsFragment.kt:98)
        at com.takisoft.fix.support.v7.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:62)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2331)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1386)
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1188)
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1071)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:115)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2380)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2338)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2245)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:703)
        at android.os.Handler.handleCallback(Handler.java:836)
        at android.os.Handler.dispatchMessage(Handler.java:103)
        at android.os.Looper.loop(Looper.java:208)
        at android.app.ActivityThread.main(ActivityThread.java:6267)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

```

**Would you like to work on the issue?**

Yes!

**Comment by codedsun** [comment]
@batbrain7 @arundhati24 What I debugged from the above crash is that, the settings from server are as 

FOR me : 

{
  "settings": {
    "prefLanguage": "default",
    "enterAsSend": "true"
  },
  "session": {"identity": {
    "type": "email",
    "name": "suneetbond91@gmail.com",
    "anonymous": false
  }},
  "accepted": true,
  "message": "Success: Showing user data",
  "lastLoginIP": "172.68.144.111"
}

The pref language is default, hence the crash is happening..

When I debugged more for @batbrain7 , the response is 

{
  "settings": {"prefLanguage": "en"},
  "session": {"identity": {
    "type": "email",
    "name": "kumar.mohit983@gmail.com",
    "anonymous": false
  }},
  "accepted": true,
  "message": "Success: Showing user data",
  "lastLoginIP": "172.68.144.111"
}

**Comment by codedsun** [comment]
@batbrain7 @arundhati24 What I debugged from the above crash is that, the settings from server are as

FOR me :

{
"settings": {
"prefLanguage": "default",
"enterAsSend": "true"
},
"session": {"identity": {
"type": "email",
"name": "sun-----",
"anonymous": false
}},
"accepted": true,
"message": "Success: Showing user data",
"lastLoginIP": "1xxx1"
}

The pref language is default, hence the crash is happening..

When I debugged more for @batbrain7 , the response is

{
"settings": {"prefLanguage": "en"},
"session": {"identity": {
"type": "email",
"name": "kuxxxx",
"anonymous": false
}},
"accepted": true,
"message": "Success: Showing user data",
"lastLoginIP": "1xx"
}

**Comment by batbrain7** [comment]
@codedsun @arundhati24 the PR #1452 is the reason for the crash

**Comment by batbrain7** [comment]
similar to the issue #1468
