### ISSUE TITLE
App crash on clicking susi button on chat screen

### ISSUE THREAD

**Issue by batbrain7** [fossasia/susi_android#1531]
**Actual Behaviour**

Whenever we click on susi button on the chat screen app crashes.

**Expected Behaviour**

App should not crash

**Steps to reproduce it**

Open the app then login then click on the susi button

**LogCat for the issue**

  ```
 Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'retrofit2.Call org.fossasia.susi.ai.rest.services.SusiService.fetchSkillMetricsData(java.lang.String, java.lang.String)' on a null object reference
        at org.fossasia.susi.ai.rest.ClientBuilder.fetchListSkillMetricsCall(ClientBuilder.java:98)
        at org.fossasia.susi.ai.data.SkillListingModel.fetchSkillMetrics(SkillListingModel.kt:61)
        at org.fossasia.susi.ai.skills.skilllisting.SkillListingPresenter.getMetrics(SkillListingPresenter.kt:47)
        at org.fossasia.susi.ai.skills.skilllisting.SkillListingFragment.onViewCreated(SkillListingFragment.kt:48)
```

**Would you like to work on the issue?**

Yes

**Comment by batbrain7** [comment]
this is after the PR #1500

**Comment by arundhati24** [comment]
Is it reproducible every time or sometimes? Didn't encounter this till now.

**Comment by batbrain7** [comment]
@arundhati24 did you pull the latest changes?
