### ISSUE TITLE
App Crash due to uninitialized lateinit property SkillListModel.kt

### ISSUE THREAD

**Issue by theLimitBreaker** [fossasia/susi_android#1742]
**Actual Behaviour**

App crashes after using 4-5 Skills from SkillsFragment through TRY IT button

**Expectedl Behaviour**

App should not crash

**Steps to reproduce it**

Use skills from SkillsFragment through TRY IT button, after using 4-5 skills., app would crash

**LogCat for the issue**

`2018-10-20 09:52:53.379 12036-12036/? E/MainApplication: kotlin.UninitializedPropertyAccessException: lateinit property authResponseCallSkills has not been initialized
        at org.fossasia.susi.ai.data.SkillListingModel.cancelFetch(SkillListingModel.kt:78)
        at org.fossasia.susi.ai.skills.skilllisting.SkillListingPresenter.onDetach(SkillListingPresenter.kt:179)
        at org.fossasia.susi.ai.skills.skilllisting.SkillListingFragment.onDestroyView(SkillListingFragment.kt:109)
        at android.support.v4.app.Fragment.performDestroyView(Fragment.java:2565)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1512)
        at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
        at android.support.v4.app.FragmentManagerImpl.dispatchDestroy(FragmentManager.java:3235)
        at android.support.v4.app.FragmentController.dispatchDestroy(FragmentController.java:265)
        at android.support.v4.app.FragmentActivity.onDestroy(FragmentActivity.java:390)
        at android.support.v7.app.AppCompatActivity.onDestroy(AppCompatActivity.java:209)
        at android.app.Activity.performDestroy(Activity.java:7245)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1250)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4370)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4401)
        at android.app.ActivityThread.-wrap5(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1649)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6501)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
    
    kotlin.UninitializedPropertyAccessException: lateinit property authResponseCallSkills has not been initialized`

**Screenshots of the issue**

<img src="https://user-images.githubusercontent.com/24780524/47251285-3d8e2c80-d450-11e8-88d4-a50323e954aa.png" width="360">

**Would you like to work on the issue?**

Yes

**Comment by atm1504** [comment]
@iamareebjamal I am looking for it if a similar problem exists till now or not.

**Comment by atm1504** [comment]
@iamareebjamal @batbrain7 @arundhati24  the app is running fine under the circumstances mentioned above. So, I think this issue doesn't exist anymore and hence can be closed.
