### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by Bhavnaharitsa** [fossasia/susi_android#2006]
**Describe the bug**

App crashes after opening setting or chat

**Expected Behaviour**
App should not crash

**Steps to reproduce it**

Open App 
1: Type some thing and CRASH
2: Go to settings and CRASH

**LogCat for the issue**

org.fossasia.susi.ai.skills.settings.ChatSettingsFragment.onCreatePreferencesFix(ChatSettingsFragment.kt:68)
        at com.takisoft.fix.support.v7.preference.PreferenceFragmentCompat.onCreate(PreferenceFragmentCompat.java:62)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2414)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:733)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:7000)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:441)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1408)
2019-03-11 06:24:58.338 29576-29576/ai.susi E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "mypackage.CategoryPreference.PreferenceCategory" on path: DexPathList[[zip file "/data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/base.apk", zip file "/data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_dependencies_apk.apk", zip file "/data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_resources_apk.apk", zip file "/data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_slice_0_apk.apk", zip file "/data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_slice_1_apk.apk", zip file "/data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_slice_2_apk.apk", zip file "/data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_slice_3_apk.apk", zip file "/data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_slice_4_apk.apk", zip file "/data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_slice_5_apk.apk", zip file "/data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_slice_6_apk.apk", zip file "/data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_slice_7_apk.apk", zip file "/data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_slice_8_apk.apk", zip file "/data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/lib/arm, /data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/base.apk!/lib/armeabi-v7a, /data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_dependencies_apk.apk!/lib/armeabi-v7a, /data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_resources_apk.apk!/lib/armeabi-v7a, /data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_slice_0_apk.apk!/lib/armeabi-v7a, /data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_slice_1_apk.apk!/lib/armeabi-v7a, /data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_slice_2_apk.apk!/lib/armeabi-v7a, /data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_slice_3_apk.apk!/lib/armeabi-v7a, /data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_slice_4_apk.apk!/lib/armeabi-v7a, /data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_slice_5_apk.apk!/lib/armeabi-v7a, /data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_slice_6_apk.apk!/lib/armeabi-v7a, /data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_slice_7_apk.apk!/lib/armeabi-v7a, /data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_slice_8_apk.apk!/lib/armeabi-v7a, /data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_slice_9_apk.apk!/lib/armeabi-v7a, /system/lib, /system/vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.support.v7.preference.PreferenceInflater.createItem(PreferenceInflater.java:231)
        at android.support.v7.preference.PreferenceInflater.createItemFromTag(PreferenceInflater.java:295)
        	... 24 more
    	Suppressed: java.io.IOException: No original dex files found for dex location (arm) /data/app/ai.susi-NG33_V-sz6gzmKYdauIDzA==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:73)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:88)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:35)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:705)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:739)
2019-03-11 06:24:58.340 29576-29576/ai.susi E/AndroidRuntime:     at android.app.LoadedApk.getResources(LoadedApk.java:980)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2420)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5996)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1791)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        		... 5 more

**Comment by androidDev-1** [comment]
@Bhavnaharitsa  Yes it is crashing on reproducing this scenario.
![Screenshot 2019-03-11 at 6 28 05 PM](https://user-images.githubusercontent.com/48344924/54125612-8492b380-442b-11e9-91da-afb19fa19747.png)

**Comment by atm1504** [comment]
@iamareebjamal @batbrain7 @arundhati24 I think this also can be closed, as this bug no longer exists.
