### ISSUE TITLE
App crashing on startup

### ISSUE THREAD

**Issue by mariobehling** [fossasia/susi_android#289]
**Actual Behaviour**

I was able to use the app a short time and login first. I tested the voice feature and the first crash happened. After that, I am not able to start Susi. It is crashing on startup.

**Expected Behaviour**

No crashes.

**Comment by amitiwary999** [comment]
@mariobehling can you post the error log because it is not crashing on my device.

**Comment by mariobehling** [comment]
@amitiwary999 Did you try with sound?

I am out at the moment. Can we have some more automated reports/logs of crashes? I opened an issue for this https://github.com/fossasia/susi_android/issues/290

**Comment by NiharG15** [comment]
@mariobehling I'm getting a crash due to a null log message. Sending a PR to fix it.

**Comment by amitiwary999** [comment]
@mariobehling Yeah I got it. 
FATAL EXCEPTION: Thread-19745
                                                                      Process: org.fossasia.susi.ai, PID: 18222
                                                                      java.util.NoSuchElementException
                                                                          at java.util.LinkedList.getFirstImpl(LinkedList.java:538)
                                                                          at java.util.LinkedList.getFirst(LinkedList.java:530)
                                                                          at org.fossasia.susi.ai.activities.MainActivity.computeOtherMessage(MainActivity.java:535)
                                                                          at org.fossasia.susi.ai.activities.MainActivity.access$1100(MainActivity.java:85)
                                                                          at org.fossasia.susi.ai.activities.MainActivity$computeThread.run(MainActivity.java:875)
