### ISSUE TITLE
App crashing in important messages activity

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#570]
**Actual Behaviour**

App crashing while deleting messages from important messages activity. 

**Expected Behaviour**

Should not crash.

**Steps to reproduce it**

Star a message. Go to important message activity and delete that message.

**LogCat for the issue**
```
FATAL EXCEPTION: main
                  Process: org.fossasia.susi.ai, PID: 16958
                  java.lang.ArrayIndexOutOfBoundsException: rowIndex is less than 0.
                      at io.realm.internal.TableView.nativeRemoveRow(Native Method)
                      at io.realm.internal.TableView.remove(TableView.java:402)
                      at io.realm.RealmResults.deleteFromRealm(RealmResults.java:255)
                      at org.fossasia.susi.ai.adapters.recycleradapters.ChatFeedRecyclerAdapter$10.execute(ChatFeedRecyclerAdapter.java:915)
                      at io.realm.Realm.executeTransaction(Realm.java:1254)
                      at org.fossasia.susi.ai.adapters.recycleradapters.ChatFeedRecyclerAdapter.removeDates(ChatFeedRecyclerAdapter.java:897)
                      at org.fossasia.susi.ai.adapters.recycleradapters.ChatFeedRecyclerAdapter.access$1600(ChatFeedRecyclerAdapter.java:96)
                      at org.fossasia.susi.ai.adapters.recycleradapters.ChatFeedRecyclerAdapter$ActionModeCallback$4.onClick(ChatFeedRecyclerAdapter.java:1043)
                      at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:161)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:148)
                      at android.app.ActivityThread.main(ActivityThread.java:5443)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:
```

**Would you like to work on the issue?**
yes
EDIT : If anyone wants to work on this, comment :)

**Comment by jig08** [comment]
@chiragw15 Thanks for opening issues, but kindly take up one at a time. Cheers !

**Comment by chiragw15** [comment]
@jig08 I was just testing the app, found some issues and reported it. I am working on them one by one. In the meanwhile If anyone else wants to work on these issues, he/she can just pick one up by commenting on them. I am happy to help :) .

**Comment by amitiwary999** [comment]
@chiragw15 I would like to work on this issue.

**Comment by chiragw15** [comment]
@amitiwary999 sure, go ahead 👍
