### ISSUE TITLE
Update implementation for updating databse (Sub issue of #664)

### ISSUE THREAD

**Issue by chiragw15** [fossasia/susi_android#679]
**Actual Behaviour**

Right now the database queries are updated asynchronously. We are using this pseudo code to create new databse entry.
1. Find the id of top element of database.
2. id++
3. add new database entry with id.

This should work fine if there is some time gap between database entries. Since, databse entry takes some time, if we add 2 database entry continuously, this will happen : 

//call for adding of 1st message
1. Find the id of top element of database.
2. id1++
3. add new database entry with id1.

4. Since database entry takes time, the above message is not entered in database. So, top element is same right now.

//call for adding 2nd element
5. Find the id of top element of database.
6. id2++
7. Now the problem arises, since top element is same in both case, id1 is equal to id2 .
8. By this time the 1st message is added to database.
9. Now, when 2nd message is tried to be inserted in database, the id already exits. 
  
**Expected Behaviour**

Propose a different implementation for updating database or a way to tackle this with this implementation. @mayank408 @amitiwary999 ideas?

Log cat 
```
io.realm.exceptions.RealmPrimaryKeyConstraintException: Value already exists: 65
    at io.realm.internal.Table.throwDuplicatePrimaryKeyException(Table.java:664)
    at io.realm.internal.Table.addEmptyRowWithPrimaryKey(Table.java:449)
    at io.realm.internal.Table.addEmptyRowWithPrimaryKey(Table.java:387)
    at io.realm.Realm.createObjectInternal(Realm.java:865)
    at io.realm.Realm.createObject(Realm.java:845)
    at org.fossasia.susi.ai.activities.MainActivity$19.execute(MainActivity.java:1100)
    at io.realm.Realm$2.run(Realm.java:1352)
    at io.realm.internal.async.BgPriorityRunnable.run(BgPriorityRunnable.java:34)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
```

**Comment by chiragw15** [comment]
Fixed in #681
