### ISSUE TITLE
App crashes sometimes in case of websearch and rss action type.

### ISSUE THREAD

**Issue by amitiwary999** [fossasia/susi_android#705]
**Actual Behaviour**

App is crashing sometimes in case of websearch and rss action type.

**Expected Behaviour**

App should not crash.

**Steps to reproduce it**

It is not happening always. 
1.Query anything such that response will be websearch or anchor type then close app and again open. 
2. Query anything such that response will be websearch or anchor type then logout and again login.
3. Query anything such that response will be websearch or anchor type then close app, open and query something.

**LogCat for the issue**

for rss action type 
java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
                                                                        at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:134)
                                                                        at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:102)
                                                                        at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:87)
                                                                        at com.bumptech.glide.Glide.with(Glide.java:629)
                                                                        at org.fossasia.susi.ai.adapters.recycleradapters.SearchResultsAdapter$1.onPos(SearchResultsAdapter.java:74)
                                                                        at com.leocardz.link.preview.library.TextCrawler$GetCode.onPostExecute(TextCrawler.java:64)
                                                                        at com.leocardz.link.preview.library.TextCrawler$GetCode.onPostExecute(TextCrawler.java:43)
                                                                        at android.os.AsyncTask.finish(AsyncTask.java:632)
                                                                        at android.os.AsyncTask.access$600(AsyncTask.java:177)
                                                                        at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5233)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:372)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)

For websearch

Process: org.fossasia.susi.ai, PID: 25779
                                                                      java.lang.IllegalArgumentException: You cannot start a load for a destroyed activity
                                                                          at com.bumptech.glide.manager.RequestManagerRetriever.assertNotDestroyed(RequestManagerRetriever.java:134)
                                                                          at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:102)
                                                                          at com.bumptech.glide.manager.RequestManagerRetriever.get(RequestManagerRetriever.java:87)
                                                                          at com.bumptech.glide.Glide.with(Glide.java:629)
                                                                          at org.fossasia.susi.ai.adapters.recycleradapters.WebSearchAdapter.onBindViewHolder(WebSearchAdapter.java:74)
                                                                          at org.fossasia.susi.ai.adapters.recycleradapters.WebSearchAdapter.onBindViewHolder(WebSearchAdapter.java:27)
                                                                          at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6279)
                                                                          at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6312)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5258)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5521)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5363)
                                                                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5359)
                                                                          at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2141)
                                                                          at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1525)

**Would you like to work on the issue?**

Yes

**Comment by chiragw15** [comment]
This is due to link previews. When the main activity is destroyed but the link is not loaded, the app crashes.
