### ISSUE TITLE
Susi Crashes on Network State Changed

### ISSUE THREAD

**Issue by addiittya2006** [fossasia/susi_android#85]
This Crash is occurring due to realm NoClassFound, on changing the Network state.
I/O Mobile data, Wi-fi.
Detected on:
Nexus 5 CM13 Android 6.0.1

![img_20161003_092010](https://cloud.githubusercontent.com/assets/7330961/19027127/f2c168cc-894a-11e6-87a6-4cded5a91bc9.jpg)

Log:
```
10-03 09:14:40.590 32622-32622/org.fossasia.susi.ai E/AndroidRuntime: FATAL EXCEPTION: main
                                                                      Process: org.fossasia.susi.ai, PID: 32622
                                                                      java.lang.RuntimeException: Unable to instantiate receiver io.realm.internal.network.NetworkStateReceiver: java.lang.ClassNotFoundException: Didn't find class "io.realm.internal.network.NetworkStateReceiver" on path: DexPathList[[zip file "/data/app/org.fossasia.susi.ai-1/base.apk"],nativeLibraryDirectories=[/data/app/org.fossasia.susi.ai-1/lib/arm, /data/app/org.fossasia.susi.ai-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                                          at android.app.ActivityThread.handleReceiver(ActivityThread.java:2750)
                                                                          at android.app.ActivityThread.-wrap14(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:148)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5466)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                       Caused by: java.lang.ClassNotFoundException: Didn't find class "io.realm.internal.network.NetworkStateReceiver" on path: DexPathList[[zip file "/data/app/org.fossasia.susi.ai-1/base.apk"],nativeLibraryDirectories=[/data/app/org.fossasia.susi.ai-1/lib/arm, /data/app/org.fossasia.susi.ai-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                                                          at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                                          at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                                          at android.app.ActivityThread.handleReceiver(ActivityThread.java:2745)
                                                                          at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1440) 
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                          at android.os.Looper.loop(Looper.java:148) 
                                                                          at android.app.ActivityThread.main(ActivityThread.java:5466) 
                                                                          at java.lang.reflect.Method.invoke(Native Method) 
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
                                                                      	Suppressed: java.lang.ClassNotFoundException: Didn't find class "io.realm.internal.network.NetworkStateReceiver" on path: DexPathList[[dex file "/data/data/org.fossasia.susi.ai/files/instant-run/dex/slice-support-annotations-24.2.1_2f4e12f50b74a0e56083d683ebcd01098f8544c5-classes.dex", dex file "/data/data/org.fossasia.susi.ai/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/org.fossasia.susi.ai/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/org.fossasia.susi.ai/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/org.fossasia.susi.ai/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/org.fossasia.susi.ai/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/org.fossasia.susi.ai/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/org.fossasia.susi.ai/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/org.fossasia.susi.ai/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/org.fossasia.susi.ai/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/org.fossasia.susi.ai/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/org.fossasia.susi.ai/files/instant-run/dex/slice-retrofit-2.1.0_cf279e13c7581267ec06efb423edffc451b4f5ff-classes.dex", dex file "/data/data/org.fossasia.susi.ai/files/instant-run/dex/slice-realm-annotations-2.0.0_07f36a1f91e6acef3721afd25e88ec47ccc4492f-classes.dex", dex file "/data/data/org.fossasia.susi.ai/files/instant-run/dex/slice-okio-1.8.0_6896106ae3c04439e55501a196384a5ecf60b5b1-classes.dex", dex file "/data/data/org.fossasia.susi.ai/files/instant-run/dex/slice-okhttp-3.3.0_068abd747c7b414410f82e22c0d0b6acbd41650d-classes.dex", dex file "/data/data/org.fossasia.susi.ai/files/instant-run/dex/slice-me.himanshusoni.chatmessageview-chat-message-view-1.0.3_7c27264fb08c446ab7c169a6481f8471c542675d-classes.dex", dex file "/data/data/org.fossasia.susi.ai/files/instant-run/dex/slice-io.realm-realm-android-library-2.0.0_62fb1293c2ee6ddc69320de50e6dbecb6871db03-classes.dex", dex file "/data/data/org.fossasia.susi.ai/files/instant-run/dex/slice-internal_impl-24.2.1_f360842d212d25afcf6d1d16c81608f47758e001-classes.dex", dex file "/data/data/org.fossasia.susi.ai/files/instant-run/dex/slice-internal_impl-24.2.1_ee35e25679ede1b1321
```

**Comment by addiittya2006** [comment]
Unfortunately, realm/realm-java#3521 & realm/realm-java#3505

**Comment by djKooks** [comment]
It looks like realm 2.x is not quite stable. How about reverting it to 1.x and upgrade after?

**Comment by gogeta95** [comment]
I'd like to work on this if any body is not working.

**Comment by pc-bszabo** [comment]
Quick and dirty solution : put this into your launcher activity OR Application=>

try {
getApplicationContext().getPackageManager().setComponentEnabledSetting(new ComponentName("your.package.name","io.realm.internal.network.NetworkStateReceiver"), PackageManager.COMPONENT_ENABLED_STATE_DISABLED, PackageManager.DONT_KILL_APP);
} catch (Exception e) {}

**Comment by Zhuinden** [comment]
Realm 2.0.1 release fixes this without having to add the broadcast receiver: https://github.com/realm/realm-java/issues/3505#issuecomment-251614137
