### ISSUE TITLE
App crashing on login and skip

### ISSUE THREAD

**Issue by hardik124** [fossasia/susi_android#912]
**Actual Behaviour**
App crashes when user tries to login or clicks on "Skip".

**Expected Behaviour**
User should be able to login.
**Steps to reproduce it* 
Click on skip on login screen or create a new user and try to login
**LogCat for the issue**

08-31 21:32:10.655 813-813/org.fossasia.susi.ai E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  Process: org.fossasia.susi.ai, PID: 813
                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{org.fossasia.susi.ai/org.fossasia.susi.ai.chat.ChatActivity}: java.lang.IllegalArgumentException: ChatMessage is not part of the schema for this Realm
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3139)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3238)
                                                                      at android.app.ActivityThread.access$1000(ActivityThread.java:197)
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                      at android.os.Looper.loop(Looper.java:145)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6862)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
                                                                   Caused by: java.lang.IllegalArgumentException: ChatMessage is not part of the schema for this Realm
                                                                      at io.realm.internal.modules.CompositeMediator.getMediator(CompositeMediator.java:172)
                                                                      at io.realm.internal.modules.CompositeMediator.getTableName(CompositeMediator.java:90)
                                                                      at io.realm.RealmSchema.getTable(RealmSchema.java:296)
                                                                      at io.realm.RealmSchema.getSchemaForClass(RealmSchema.java:316)
                                                                      at io.realm.RealmQuery.<init>(RealmQuery.java:138)
                                                                      at io.realm.RealmQuery.createQuery(RealmQuery.java:87)
                                                                      at io.realm.Realm.where(Realm.java:1214)
                                                                      at org.fossasia.susi.ai.data.db.DatabaseRepository.getMessageCount(DatabaseRepository.kt:25)
                                                                      at org.fossasia.susi.ai.chat.ChatPresenter.setUp(ChatPresenter.kt:57)
                                                                      at org.fossasia.susi.ai.chat.ChatActivity.setUpUI(ChatActivity.kt:97)
                                                                      at org.fossasia.susi.ai.chat.ChatActivity.onCreate(ChatActivity.kt:81)
                                                                      at android.app.Activity.performCreate(Activity.java:6536)
                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3092)
                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3238) 
                                                                      at android.app.ActivityThread.access$1000(ActivityThread.java:197) 
                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                      at android.os.Looper.loop(Looper.java:145) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:6862) 
                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199) 

**Would you like to work on the issue?**
Yes

**Comment by chiragw15** [comment]
@hardik124 what are the exact steps to reproduce this? Does installing the app and skipping the login produces this crash? Try checking again and make sure you have latest code and you haven't changed anything.

**Comment by hardik124** [comment]
Yes @chiragw15 , I did not change anything. I signed up for a new account and as I logged in it crashed.Also when I click on the skip in the login screen it crashes. 
I checked the error is related to the plugin in realm.

**Comment by chashmeetsingh** [comment]
@hardik124 I suppose it's related to the realm migrations. Try uninstalling and reinstalling the app, it should work fine then.

**Comment by hardik124** [comment]
@chashmeetsingh  I tried that multiple times.

**Comment by hardik124** [comment]
@chashmeetsingh @chiragw15  Did anyone of you encounter this?

**Comment by hardik124** [comment]
I figured out that the problem was with apt plugin. So I removed it and used kapt instead.
